#!/usr/bin/env bats

# BATS tests fuer dotenv_get in den Kapitel-22-Skripten (MEM-327).
#
# dotenv_get bildet Symfonys Dotenv::bootEnv() fuer die CLI nach. Die
# Erwartungen hier stammen aus der Messung in Shopware 6.6.10.6 (MEM-327,
# 22 Szenarien, CLI-Sonde ueber dieselbe Runtime wie bin/console):
#   Umgebung > .env.local.php > .env.<APP_ENV>.local > .env.<APP_ENV>
#   > .env.local > .env; APP_ENV=dev in .env.prod gewinnt; ohne APP_ENV: dev.
#
# Positive Zusicherungen pruefen Wert UND Quelle auf Gleichheit, damit ein
# "Kein Treffer" nie als Treffer durchgeht.

DIR="./chapters/22-haeufigste-probleme/scripts"

# Die Skripte, die dotenv_get wortgleich tragen.
DOTENV_SCRIPTS=(
    audit-themes.sh check-debug-mode.sh check-elasticsearch.sh
    detect-n1-queries.sh diagnose-slow-queries.sh profile-cart.sh
    test-session-lock.sh
)

setup() {
    [ -d "$DIR" ] || skip "Script directory not found: $DIR"
    shop="$BATS_TEST_TMPDIR/shop"
    mkdir -p "$shop"
    stub_dir="$BATS_TEST_TMPDIR/bin"
    mkdir -p "$stub_dir"
    # Die Funktion aus einem Skript ziehen; der Drift-Test haelt die Kopien gleich.
    sed -n '/^# >>> dotenv_get/,/^# <<< dotenv_get/p' "$DIR/check-debug-mode.sh" \
        > "$BATS_TEST_TMPDIR/dotenv_get.sh"
}

# get NAME [VAR=wert ...]: dotenv_get in einer sauberen Umgebung aufrufen.
# Ausgabe: "<wert>|<quelle>".
get() {
    local name="$1"; shift
    env -i PATH="$PATH" SHOP_PATH="$shop" "$@" bash -c '
        set -euo pipefail
        source "$1"
        dotenv_get "$2"
        printf "%s|%s\n" "$DOTENV_VALUE" "$DOTENV_SOURCE"
    ' _ "$BATS_TEST_TMPDIR/dotenv_get.sh" "$name"
}

# note NAME [VAR=wert ...]: nur DOTENV_NOTE.
note() {
    local name="$1"; shift
    env -i PATH="$PATH" SHOP_PATH="$shop" "$@" bash -c '
        set -euo pipefail
        source "$1"
        dotenv_get "$2"
        printf "%s\n" "$DOTENV_NOTE"
    ' _ "$BATS_TEST_TMPDIR/dotenv_get.sh" "$name"
}

# ---------------------------------------------------------------------------
# Drift und Altlasten
# ---------------------------------------------------------------------------

@test "dotenv_get steht in allen Skripten wortgleich" {
    ref=$(sed -n '/^# >>> dotenv_get/,/^# <<< dotenv_get/p' "$DIR/check-debug-mode.sh")
    [ -n "$ref" ]
    for s in "${DOTENV_SCRIPTS[@]}"; do
        got=$(sed -n '/^# >>> dotenv_get/,/^# <<< dotenv_get/p' "$DIR/$s")
        [ "$got" == "$ref" ] || { echo "abweichend: $s"; return 1; }
    done
    # ... und in keinem weiteren Skript ohne Eintrag in der Liste.
    run grep -l '^# >>> dotenv_get' "$DIR"/*.sh
    [ "$(printf '%s\n' "$output" | wc -l)" -eq "${#DOTENV_SCRIPTS[@]}" ]
}

@test "kein Skript liest nur .env und .env.local (altes Muster)" {
    run grep -n '"${SHOP_PATH}/.env" "${SHOP_PATH}/.env.local"; do' "$DIR"/*.sh
    [ "$status" -ne 0 ] || { echo "$output"; return 1; }
}

# ---------------------------------------------------------------------------
# dotenv_get: jede Quelle einzeln
# ---------------------------------------------------------------------------

@test "dotenv_get: nur .env" {
    printf 'APP_ENV=prod\nX=aus-env\n' > "$shop/.env"
    [ "$(get X)" == "aus-env|.env" ]
}

@test "dotenv_get: .env.local schlaegt .env" {
    printf 'APP_ENV=prod\nX=aus-env\n' > "$shop/.env"
    printf 'X=aus-local\n' > "$shop/.env.local"
    [ "$(get X)" == "aus-local|.env.local" ]
}

@test "dotenv_get: .env.prod schlaegt .env.local (gemessen: es_prod, dbg_local0_prod1)" {
    printf 'APP_ENV=prod\nX=aus-env\n' > "$shop/.env"
    printf 'X=aus-local\n' > "$shop/.env.local"
    printf 'X=aus-prod\n' > "$shop/.env.prod"
    [ "$(get X)" == "aus-prod|.env.prod" ]
}

@test "dotenv_get: .env.prod.local schlaegt .env.prod" {
    printf 'APP_ENV=prod\nX=aus-env\n' > "$shop/.env"
    printf 'X=aus-prod\n' > "$shop/.env.prod"
    printf 'X=aus-prod-local\n' > "$shop/.env.prod.local"
    [ "$(get X)" == "aus-prod-local|.env.prod.local" ]
}

@test "dotenv_get: export-Praefix zaehlt (gemessen: es_export)" {
    printf 'APP_ENV=prod\nX=aus-env\n' > "$shop/.env"
    printf 'export X=aus-export\n' > "$shop/.env.local"
    [ "$(get X)" == "aus-export|.env.local" ]
}

@test "dotenv_get: .env.local.php ersetzt alle .env-Dateien (gemessen: es_php_vs_prodlocal)" {
    printf 'APP_ENV=prod\nX=aus-env\n' > "$shop/.env"
    printf 'X=aus-prod-local\n' > "$shop/.env.prod.local"
    cat > "$shop/.env.local.php" <<'PHP'
<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'X' => 'aus-php',
);
PHP
    [ "$(get X)" == "aus-php|.env.local.php" ]
}

@test "dotenv_get: fehlt die Variable in .env.local.php, gilt keine .env-Datei" {
    printf 'APP_ENV=prod\nX=aus-env\n' > "$shop/.env"
    printf "<?php return array (\n  'APP_ENV' => 'prod',\n);\n" > "$shop/.env.local.php"
    [ "$(get X)" == "|" ]
}

@test "dotenv_get: .env.local.php mit maskiertem Apostroph" {
    printf "<?php return array (\n  'X' => 'a\\\\'b',\n);\n" > "$shop/.env.local.php"
    [ "$(get X)" == "a'b|.env.local.php" ]
}

@test "dotenv_get: die Umgebung schlaegt jede Datei, auch .env.local.php" {
    printf 'APP_ENV=prod\nX=aus-env\n' > "$shop/.env"
    printf "<?php return array (\n  'X' => 'aus-php',\n);\n" > "$shop/.env.local.php"
    [ "$(get X X=aus-umgebung)" == "aus-umgebung|Umgebung" ]
}

@test "dotenv_get: anderes APP_ENV in der Umgebung als in .env.local.php - Datei gilt nicht (gemessen: php_env_mismatch)" {
    printf 'APP_ENV=prod\nX=aus-env\n' > "$shop/.env"
    printf "<?php return array (\n  'APP_ENV' => 'prod',\n  'X' => 'aus-php',\n);\n" > "$shop/.env.local.php"
    [ "$(get X APP_ENV=dev)" == "aus-env|.env" ]
    [ "$(get X APP_ENV=prod)" == "aus-php|.env.local.php" ]
}

@test "dotenv_get: .env.local.php ohne APP_ENV gilt auch bei APP_ENV in der Umgebung" {
    printf 'APP_ENV=prod\nX=aus-env\n' > "$shop/.env"
    printf "<?php return array (\n  'X' => 'aus-php',\n);\n" > "$shop/.env.local.php"
    [ "$(get X APP_ENV=dev)" == "aus-php|.env.local.php" ]
}

@test "dotenv_get: .env.local.php in fremdem Format = Quelle genannt, Wert leer, Format-Hinweis" {
    printf "<?php return array (\n  'APP_DEBUG' => 1,\n);\n" > "$shop/.env.local.php"
    [ "$(get APP_DEBUG)" == "|.env.local.php" ]
    [ "$(note APP_DEBUG)" == "Format" ]
}

@test "dotenv_get: \$-Verweis wird gemeldet, in einfachen Anfuehrungszeichen nicht" {
    printf 'APP_ENV=prod\nA=${B}\nC="x$D"\nE='"'"'$F'"'"'\nG=ohne\n' > "$shop/.env"
    [ "$(note A)" == "Verweis" ]
    [ "$(note C)" == "Verweis" ]
    [ "$(note E)" == "" ]
    [ "$(note G)" == "" ]
}

@test "dotenv_get: spaetere Datei ohne Verweis hebt den Hinweis auf" {
    printf 'APP_ENV=prod\nX=${Y}\n' > "$shop/.env"
    printf 'X=fest\n' > "$shop/.env.local"
    [ "$(get X)" == "fest|.env.local" ]
    [ "$(note X)" == "" ]
}

@test "dotenv_get: nicht lesbare Datei beendet mit 69 (Symfony scheitert ebenso)" {
    [ "$(id -u)" -ne 0 ] || skip "root liest jede Datei"
    printf 'APP_ENV=prod\n' > "$shop/.env"
    printf 'APP_DEBUG=1\n' > "$shop/.env.local"
    chmod 0 "$shop/.env.local"
    run env -i PATH="$PATH" SHOP_PATH="$shop" bash -c 'set -euo pipefail; source "$1"; dotenv_get APP_DEBUG' _ "$BATS_TEST_TMPDIR/dotenv_get.sh"
    chmod 644 "$shop/.env.local"
    [ "$status" -eq 69 ]
    [[ "$output" == *"Nicht lesbar: $shop/.env.local"* ]]
}

# ---------------------------------------------------------------------------
# APP_ENV: Dateiwahl und Wert
# ---------------------------------------------------------------------------

@test "dotenv_get: APP_ENV=dev in .env.prod gewinnt, die Dateiwahl bleibt prod (gemessen: env_prod_dev)" {
    printf 'APP_ENV=prod\n' > "$shop/.env"
    printf 'APP_ENV=dev\n' > "$shop/.env.prod"
    printf 'Y=aus-prod-local\n' > "$shop/.env.prod.local"
    printf 'Y=aus-dev\n' > "$shop/.env.dev"
    [ "$(get APP_ENV)" == "dev|.env.prod" ]
    [ "$(get Y)" == "aus-prod-local|.env.prod.local" ]
}

@test "dotenv_get: ohne APP_ENV liest es die dev-Dateien, nicht die prod-Dateien (gemessen: env_unset)" {
    printf 'X=aus-env\n' > "$shop/.env"
    printf 'X=aus-prod\n' > "$shop/.env.prod"
    printf 'X=aus-dev\n' > "$shop/.env.dev"
    [ "$(get X)" == "aus-dev|.env.dev" ]
    [ "$(get APP_ENV)" == "|" ]
}

@test "dotenv_get: APP_ENV aus .env.local waehlt die Dateien (gemessen: env_local_prod)" {
    printf 'APP_ENV=dev\nX=aus-env\n' > "$shop/.env"
    printf 'APP_ENV=prod\n' > "$shop/.env.local"
    printf 'X=aus-prod\n' > "$shop/.env.prod"
    printf 'X=aus-dev\n' > "$shop/.env.dev"
    [ "$(get X)" == "aus-prod|.env.prod" ]
}

@test "dotenv_get: APP_ENV aus der Umgebung waehlt die Dateien" {
    printf 'APP_ENV=dev\nX=aus-env\n' > "$shop/.env"
    printf 'X=aus-prod\n' > "$shop/.env.prod"
    printf 'X=aus-dev\n' > "$shop/.env.dev"
    [ "$(get X APP_ENV=prod)" == "aus-prod|.env.prod" ]
}

@test "dotenv_get: APP_ENV aus der Umgebung schlaegt APP_ENV aus .env.local bei der Dateiwahl" {
    printf 'APP_ENV=prod\nX=aus-env\n' > "$shop/.env"
    printf 'APP_ENV=dev\n' > "$shop/.env.local"
    printf 'X=aus-prod\n' > "$shop/.env.prod"
    printf 'X=aus-dev\n' > "$shop/.env.dev"
    [ "$(get X APP_ENV=prod)" == "aus-prod|.env.prod" ]
}

@test "dotenv_get: bei APP_ENV=local keine weiteren Dateien" {
    printf 'APP_ENV=local\nX=aus-env\n' > "$shop/.env"
    printf 'X=aus-local-local\n' > "$shop/.env.local.local"
    [ "$(get X)" == "aus-env|.env" ]
}

@test "dotenv_get: .env schlaegt .env.dist, wenn beide da sind" {
    printf 'APP_ENV=prod\nX=aus-env\n' > "$shop/.env"
    printf 'APP_ENV=prod\nX=aus-dist\n' > "$shop/.env.dist"
    [ "$(get X)" == "aus-env|.env" ]
}

@test "dotenv_get: bei APP_ENV=test entfaellt .env.local" {
    printf 'APP_ENV=test\nX=aus-env\n' > "$shop/.env"
    printf 'X=aus-local\n' > "$shop/.env.local"
    [ "$(get X)" == "aus-env|.env" ]
}

@test "dotenv_get: ohne .env, .env.dist und .env.local.php liest Shopware keine Datei" {
    printf 'X=aus-local\n' > "$shop/.env.local"
    [ "$(get X)" == "|" ]
}

@test "dotenv_get: .env.dist, wenn .env fehlt" {
    printf 'APP_ENV=prod\nX=aus-dist\n' > "$shop/.env.dist"
    [ "$(get X)" == "aus-dist|.env.dist" ]
}

@test "dotenv_get: Anfuehrungszeichen und Kommentar hinter dem Wert" {
    printf 'APP_ENV=prod\nA="mit leer"\nB='"'"'einfach'"'"'\nC=wert # kommentar\n' > "$shop/.env"
    [ "$(get A)" == "mit leer|.env" ]
    [ "$(get B)" == "einfach|.env" ]
    [ "$(get C)" == "wert|.env" ]
}

@test "dotenv_get: zweimal in derselben Datei - die letzte Zuweisung gilt" {
    printf 'APP_ENV=prod\nX=eins\nX=zwei\n' > "$shop/.env"
    printf "<?php return array (\n  'X' => 'eins',\n  'X' => 'zwei',\n);\n" > "$shop/.env.local.php"
    [ "$(get X)" == "zwei|.env.local.php" ]
    rm "$shop/.env.local.php"
    [ "$(get X)" == "zwei|.env" ]
}

@test "dotenv_get: aehnliche Namen zaehlen nicht (X_Y ist nicht X)" {
    printf 'APP_ENV=prod\nX_Y=falsch\nXX=falsch\n' > "$shop/.env"
    [ "$(get X)" == "|" ]
}

@test "dotenv_get: laeuft unter set -euo pipefail ohne jede Datei durch" {
    [ "$(get X)" == "|" ]
}

# ---------------------------------------------------------------------------
# check-debug-mode.sh
# ---------------------------------------------------------------------------

# curl-Stub: $1 = Antwort der unbekannten API-Route, oder FAIL.
debug_stub() {
    printf '%s' "$1" > "$BATS_TEST_TMPDIR/api-body"
    cat > "$stub_dir/curl" <<EOF
#!/bin/bash
printf '%s\n' "\$@" >> "$BATS_TEST_TMPDIR/curl-args"
[ "\$(cat "$BATS_TEST_TMPDIR/api-body")" = FAIL ] && exit 7
cat "$BATS_TEST_TMPDIR/api-body"
EOF
    chmod +x "$stub_dir/curl"
}
NO_TRACE='{"errors":[{"code":"0","status":"404","title":"Not Found","detail":"No route found"}]}'
WITH_TRACE='{"errors":[{"code":"0","status":"404","title":"Not Found","detail":"No route found","trace":[{"file":"x"}]}]}'

run_debug() {
    run env -u APP_ENV -u APP_DEBUG PATH="$stub_dir:$PATH" bash "$DIR/check-debug-mode.sh" http://example.test "$shop"
}

@test "check-debug-mode.sh: APP_ENV=dev in .env.prod = Problem, Quelle genannt" {
    printf 'APP_ENV=prod\n' > "$shop/.env"
    printf 'APP_ENV=dev\n' > "$shop/.env.prod"
    debug_stub "$NO_TRACE"
    run_debug
    [ "$status" -eq 1 ]
    [[ "$output" == *"=> APP_ENV=dev (aus .env.prod)"* ]]
    [[ "$output" == *"KRITISCH: APP_ENV=dev statt prod"* ]]
}

@test "check-debug-mode.sh: APP_DEBUG=1 in .env.prod.local schlaegt APP_DEBUG=0 in .env.local" {
    printf 'APP_ENV=prod\n' > "$shop/.env"
    printf 'APP_DEBUG=0\n' > "$shop/.env.local"
    printf 'APP_DEBUG=1\n' > "$shop/.env.prod.local"
    debug_stub "$NO_TRACE"
    run_debug
    [ "$status" -eq 1 ]
    [[ "$output" == *"=> APP_DEBUG=1 (aus .env.prod.local)"* ]]
    [[ "$output" == *"KRITISCH: APP_DEBUG an"* ]]
    [[ "$output" == *".env.local: APP_DEBUG=0"*".env.prod.local: APP_DEBUG=1"* ]]
}

@test "check-debug-mode.sh: .env.local.php mit prod schlaegt APP_ENV=dev in .env" {
    printf 'APP_ENV=dev\n' > "$shop/.env"
    printf "<?php return array (\n  'APP_ENV' => 'prod',\n  'APP_DEBUG' => '0',\n);\n" > "$shop/.env.local.php"
    debug_stub "$NO_TRACE"
    run_debug
    [ "$status" -eq 0 ]
    [[ "$output" == *"=> APP_ENV=prod (aus .env.local.php)"* ]]
    [[ "$output" == *".env.local.php vorhanden"* ]]
}

@test "check-debug-mode.sh: ohne APP_ENV gilt dev, Debug folgt daraus" {
    printf 'X=1\n' > "$shop/.env"
    debug_stub "$NO_TRACE"
    run_debug
    [ "$status" -eq 1 ]
    [[ "$output" == *"APP_ENV nirgends gesetzt — Symfony nimmt dev"* ]]
    [[ "$output" == *"APP_DEBUG nicht gesetzt — folgt aus APP_ENV=dev: 1"* ]]
}

@test "check-debug-mode.sh: prod ohne APP_DEBUG = Debug aus, Exit 0" {
    printf 'APP_ENV=prod\n' > "$shop/.env"
    debug_stub "$NO_TRACE"
    run_debug
    [ "$status" -eq 0 ]
    [[ "$output" == *"APP_DEBUG nicht gesetzt — folgt aus APP_ENV=prod: 0"* ]]
    [[ "$output" == *"✓ Kein Stacktrace"* ]]
}

@test "check-debug-mode.sh: APP_ENV aus der Umgebung schlaegt .env" {
    printf 'APP_ENV=dev\n' > "$shop/.env"
    debug_stub "$NO_TRACE"
    run env -u APP_DEBUG APP_ENV=prod PATH="$stub_dir:$PATH" bash "$DIR/check-debug-mode.sh" http://example.test "$shop"
    [ "$status" -eq 0 ]
    [[ "$output" == *"=> APP_ENV=prod (aus Umgebung)"* ]]
}

@test "check-debug-mode.sh: Stacktrace in der API-Fehlerantwort = Debug im Web an (gemessen: dbg_fpm)" {
    printf 'APP_ENV=prod\n' > "$shop/.env"
    debug_stub "$WITH_TRACE"
    run_debug
    [ "$status" -eq 1 ]
    [[ "$output" == *"Debug ist im Web an"* ]]
    [[ "$output" != *"Debug ist im Web aus"* ]]
}

@test "check-debug-mode.sh: Webserver nicht erreichbar oder keine API = nicht geprueft, kein Urteil" {
    printf 'APP_ENV=prod\n' > "$shop/.env"
    for body in FAIL '<html>nginx</html>'; do
        debug_stub "$body"
        run_debug
        [ "$status" -eq 0 ]
        [[ "$output" == *"nicht geprueft"* ]]
        [[ "$output" != *"Debug ist im Web"* ]]
        [[ "$output" == *"Nicht geprueft: Debug (Webserver) APP_ENV (Webserver)."* ]]
        [[ "$output" != *"korrekt konfiguriert"* ]]
    done
}

@test "check-debug-mode.sh: folgt Weiterleitungen (curl -L) (Review B H1)" {
    printf 'APP_ENV=prod\n' > "$shop/.env"
    debug_stub "$NO_TRACE"
    run_debug
    grep -qx -- '-sSL' "$BATS_TEST_TMPDIR/curl-args"
}

@test "check-debug-mode.sh: APP_DEBUG=yes, =2 und =-1 sind an" {
    for v in yes 2 -1; do
        printf 'APP_ENV=prod\nAPP_DEBUG=%s\n' "$v" > "$shop/.env"
        debug_stub "$NO_TRACE"
        run_debug
        [ "$status" -eq 1 ] || { echo "APP_DEBUG=$v"; return 1; }
        [[ "$output" == *"KRITISCH: APP_DEBUG an"* ]]
    done
}

@test "check-debug-mode.sh: APP_DEBUG mit \$-Verweis wird nicht bewertet" {
    printf 'APP_ENV=prod\nAPP_DEBUG=${X:-1}\n' > "$shop/.env"
    debug_stub "$NO_TRACE"
    run_debug
    [ "$status" -eq 0 ]
    [[ "$output" == *"APP_DEBUG nicht bewertet"* ]]
    [[ "$output" != *"APP_DEBUG aus"* ]]
    [[ "$output" == *"Nicht geprueft: APP_DEBUG (CLI)"* ]]
}

@test "check-debug-mode.sh: .env.local.php ohne APP_ENV = CLI prod mit Debug, Web dev" {
    printf "<?php return array (\n  'X' => '1',\n);\n" > "$shop/.env.local.php"
    debug_stub "$NO_TRACE"
    run_debug
    [ "$status" -eq 1 ]
    [[ "$output" == *".env.local.php ohne APP_ENV — bin/console laeuft in prod mit Debug"* ]]
}

@test "check-debug-mode.sh: Empfehlung ohne assets:install/theme:compile (Review A1)" {
    printf 'APP_ENV=dev\n' > "$shop/.env"
    debug_stub "$NO_TRACE"
    run_debug
    [ "$status" -eq 1 ]
    [[ "$output" != *"theme:compile"* ]]
    [[ "$output" != *"assets:install"* ]]
    [[ "$output" == *"cache:clear:all ab Shopware 6.6.8.0"* ]]
}

@test "check-debug-mode.sh: Empfehlung nennt die Reihenfolge, nicht nur .env.local" {
    printf 'APP_ENV=dev\n' > "$shop/.env"
    debug_stub "$NO_TRACE"
    run_debug
    [ "$status" -eq 1 ]
    [[ "$output" == *".env < .env.local <"*".env.prod < .env.prod.local"* ]]
    [[ "$output" == *"composer dump-env prod"* ]]
}

@test "check-debug-mode.sh: ohne .env, .env.dist und .env.local.php Exit 69" {
    printf 'APP_ENV=prod\n' > "$shop/.env.local"
    debug_stub "$NO_TRACE"
    run_debug
    [ "$status" -eq 69 ]
}

# ---------------------------------------------------------------------------
# check-elasticsearch.sh
# ---------------------------------------------------------------------------

# curl-Stub: Admin-Seite mit storefrontEsEnable=$1 (oder NONE), ES antwortet gesund.
# Jeder Aufruf landet mit URL in calls. STUB_INDICES und STUB_ALIAS (leer =
# kein Alias) aendern die Antworten auf _cat/indices und _cat/aliases.
es_stub() {
    cat > "$stub_dir/curl" <<EOF
#!/bin/bash
url="\${@: -1}"
echo "\$url" >> "$BATS_TEST_TMPDIR/calls"
printf '%s\n' "\$@" >> "$BATS_TEST_TMPDIR/curl-args"
case "\$url" in
    */admin) [ "$1" = NONE ] && echo '<html></html>' || echo "      storefrontEsEnable: $1," ;;
    */_cluster/health) echo '{"status":"green"}' ;;
    */_cat/indices/*) printf '%b\n' "\${STUB_INDICES-sw_product_1 100 1mb}" ;;
    */_cat/aliases/*) [ -n "\${STUB_ALIAS-sw_product_1}" ] && echo "\${STUB_ALIAS-sw_product_1}" ;;
    *) printf '%s\n' "\${STUB_ROOT-{\"version\":{\"number\":\"2.19.1\",\"distribution\":\"opensearch\"}}}" ;;
esac
EOF
    chmod +x "$stub_dir/curl"
}

run_es() {
    run env -u SHOPWARE_ES_ENABLED -u OPENSEARCH_URL -u APP_ENV PATH="$stub_dir:$PATH" \
        bash "$DIR/check-elasticsearch.sh" http://example.test "$shop"
}

@test "check-elasticsearch.sh: SHOPWARE_ES_ENABLED und OPENSEARCH_URL aus .env.prod.local (gemessen: es_prodlocal)" {
    printf 'APP_ENV=prod\nSHOPWARE_ES_ENABLED=0\nOPENSEARCH_URL=http://alt:9200\n' > "$shop/.env"
    printf 'SHOPWARE_ES_ENABLED=1\nOPENSEARCH_URL=http://neu:9200\n' > "$shop/.env.prod.local"
    es_stub true
    run_es
    [ "$status" -eq 0 ]
    [[ "$output" == *"SHOPWARE_ES_ENABLED          = 1 (.env.prod.local)"* ]]
    grep -qx 'http://neu:9200' "$BATS_TEST_TMPDIR/calls"
    ! grep -q 'alt:9200' "$BATS_TEST_TMPDIR/calls"
}

@test "check-elasticsearch.sh: OPENSEARCH_URL aus .env.local.php, .env.local.php-Hinweis" {
    printf 'APP_ENV=prod\nSHOPWARE_ES_ENABLED=0\nOPENSEARCH_URL=http://alt:9200\n' > "$shop/.env"
    printf "<?php return array (\n  'APP_ENV' => 'prod',\n  'SHOPWARE_ES_ENABLED' => '1',\n  'OPENSEARCH_URL' => 'http://php:9200',\n);\n" > "$shop/.env.local.php"
    es_stub true
    run_es
    [ "$status" -eq 0 ]
    [[ "$output" == *"OPENSEARCH_URL               = http://php:9200 (.env.local.php)"* ]]
    [[ "$output" == *".env.local.php vorhanden"* ]]
    grep -qx 'http://php:9200' "$BATS_TEST_TMPDIR/calls"
}

@test "check-elasticsearch.sh: Webserver an, CLI aus = uneins, Exit 1 (gemessen: es_fpm)" {
    printf 'APP_ENV=prod\nSHOPWARE_ES_ENABLED=0\n' > "$shop/.env"
    es_stub true
    run_es
    [ "$status" -eq 1 ]
    [[ "$output" == *"storefrontEsEnable: true"* ]]
    [[ "$output" == *"Webserver (true) und CLI (false) sind uneins"* ]]
    [[ "$output" != *"Die Suche laeuft NICHT"* ]]
}

@test "check-elasticsearch.sh: Webserver aus, CLI an = uneins und Suche nicht ueber ES (gemessen: es_fpm_vs_local)" {
    printf 'APP_ENV=prod\nSHOPWARE_ES_ENABLED=1\n' > "$shop/.env"
    es_stub false
    run_es
    [ "$status" -eq 1 ]
    [[ "$output" == *"Webserver (false) und CLI (true) sind uneins"* ]]
    [[ "$output" == *"Die Suche laeuft NICHT ueber Elasticsearch"* ]]
}

@test "check-elasticsearch.sh: ohne storefrontEsEnable entscheidet die CLI-Sicht" {
    printf 'APP_ENV=prod\nSHOPWARE_ES_ENABLED=true\n' > "$shop/.env"
    es_stub NONE
    run_es
    [ "$status" -eq 0 ]
    [[ "$output" == *"Kein storefrontEsEnable"* ]]
    [[ "$output" != *"uneins"* ]]
}

@test "check-elasticsearch.sh: Umgebung der Shell als Ursache genannt (Review B N7)" {
    printf 'APP_ENV=prod\nSHOPWARE_ES_ENABLED=0\n' > "$shop/.env"
    es_stub false
    run env -u OPENSEARCH_URL -u APP_ENV SHOPWARE_ES_ENABLED=1 PATH="$stub_dir:$PATH" \
        bash "$DIR/check-elasticsearch.sh" http://example.test "$shop"
    [ "$status" -eq 1 ]
    [[ "$output" == *"aus der Umgebung dieser Shell"* ]]
    [[ "$output" != *"Der Webserver setzt eigene Werte"* ]]
}

@test "check-elasticsearch.sh: Admin-Pfad aus SHOPWARE_ADMINISTRATION_PATH_NAME, curl -L" {
    printf 'APP_ENV=prod\nSHOPWARE_ES_ENABLED=1\nSHOPWARE_ADMINISTRATION_PATH_NAME=verwaltung\n' > "$shop/.env"
    es_stub true
    run_es
    grep -qx 'http://example.test/verwaltung' "$BATS_TEST_TMPDIR/calls"
    # Die Anmeldeseite mit -L holen (Weiterleitung http -> https), Review B M4.
    grep -qx -- '-sSL' "$BATS_TEST_TMPDIR/curl-args"
}

@test "check-elasticsearch.sh: SHOPWARE_ES_ENABLED=0.5 zaehlt als an (env(bool:))" {
    printf 'APP_ENV=prod\nSHOPWARE_ES_ENABLED=0.5\n' > "$shop/.env"
    es_stub true
    run_es
    [ "$status" -eq 0 ]
    [[ "$output" != *"uneins"* ]]
}

@test "check-elasticsearch.sh: OPENSEARCH_URL mit \$-Verweis wird nicht angefragt" {
    printf 'APP_ENV=prod\nSHOPWARE_ES_ENABLED=1\nOPENSEARCH_URL=http://${ES_HOST_NAME}:9200\n' > "$shop/.env"
    es_stub true
    run_es
    [[ "$output" == *"OPENSEARCH_URL               = http://\${ES_HOST_NAME}:9200 (.env) enthaelt einen"* ]]
    ! grep -q 'ES_HOST_NAME' "$BATS_TEST_TMPDIR/calls"
}

@test "check-elasticsearch.sh: ES_ENABLED nirgends gesetzt = nicht gesetzt, Suche nicht ueber ES" {
    printf 'APP_ENV=prod\n' > "$shop/.env"
    es_stub NONE
    run_es
    [ "$status" -eq 1 ]
    [[ "$output" == *"SHOPWARE_ES_ENABLED          = (nicht gesetzt)"* ]]
    [[ "$output" == *"Die Suche laeuft NICHT ueber Elasticsearch"* ]]
}

@test "check-elasticsearch.sh: Alias auf gesundem Index wird genannt, Exit 0" {
    printf 'APP_ENV=prod\nSHOPWARE_ES_ENABLED=1\n' > "$shop/.env"
    es_stub true
    run_es
    [ "$status" -eq 0 ]
    grep -qx 'http://localhost:9200/_cat/aliases/sw_product?h=index' "$BATS_TEST_TMPDIR/calls"
    printf '%s\n' "$output" | grep -qxF '   Alias sw_product -> sw_product_1 (100 Dokumente)'
}

@test "check-elasticsearch.sh: Alias auf leerem Index = Exit 1 (gemessen: es:index ohne --no-queue, MEM-330)" {
    printf 'APP_ENV=prod\nSHOPWARE_ES_ENABLED=1\n' > "$shop/.env"
    es_stub true
    STUB_INDICES='sw_product_2 234 1mb\nsw_product_3 0 1kb' STUB_ALIAS=sw_product_3 run_es
    [ "$status" -eq 1 ]
    printf '%s\n' "$output" | grep -qxF '   Alias sw_product -> sw_product_3 (0 Dokumente)'
    [[ "$output" == *"Der Alias zeigt auf einen leeren Index"* ]]
}

@test "check-elasticsearch.sh: leerer Neuaufbau-Index neben gefuelltem Alias ist kein Befund" {
    printf 'APP_ENV=prod\nSHOPWARE_ES_ENABLED=1\n' > "$shop/.env"
    es_stub true
    STUB_INDICES='sw_product_2 234 1mb\nsw_product_3 0 1kb' STUB_ALIAS=sw_product_2 run_es
    [ "$status" -eq 0 ]
    printf '%s\n' "$output" | grep -qxF '   Alias sw_product -> sw_product_2 (234 Dokumente)'
}

@test "check-elasticsearch.sh: Elasticsearch ohne distribution-Feld laeuft durch (MEM-330, ES 8.15.3 live)" {
    printf 'APP_ENV=prod\nSHOPWARE_ES_ENABLED=1\n' > "$shop/.env"
    es_stub true
    # Wortlaut der Wurzelantwort von Elasticsearch 8.15.3 (gekuerzt, mehrzeilig)
    STUB_ROOT=$'{\n  "name" : "n1",\n  "version" : {\n    "number" : "8.15.3",\n    "build_flavor" : "default"\n  },\n  "tagline" : "You Know, for Search"\n}' run_es
    [ "$status" -eq 0 ]
    printf '%s\n' "$output" | grep -qxF '   erreichbar — elasticsearch 8.15.3'
    printf '%s\n' "$output" | grep -qxF 'Elasticsearch ist aktiv, erreichbar und hat Indizes.'
}

@test "check-elasticsearch.sh: OpenSearch nennt seine Distribution" {
    printf 'APP_ENV=prod\nSHOPWARE_ES_ENABLED=1\n' > "$shop/.env"
    es_stub true
    run_es
    [ "$status" -eq 0 ]
    printf '%s\n' "$output" | grep -qxF '   erreichbar — opensearch 2.19.1'
}

@test "check-elasticsearch.sh: Index ohne Alias = Exit 1" {
    printf 'APP_ENV=prod\nSHOPWARE_ES_ENABLED=1\n' > "$shop/.env"
    es_stub true
    STUB_ALIAS= run_es
    [ "$status" -eq 1 ]
    [[ "$output" == *"Kein Alias sw_product: Die Suche findet keinen Index."* ]]
}

@test "check-elasticsearch.sh: Abhilfe schaltet SHOPWARE_ES_ENABLED erst nach es:index ein (MEM-330)" {
    printf 'APP_ENV=prod\nSHOPWARE_ES_ENABLED=0\n' > "$shop/.env"
    es_stub false
    run_es
    [ "$status" -eq 1 ]
    idx=$(printf '%s\n' "$output" | grep -nxF '  bin/console es:index --no-queue' | cut -d: -f1)
    on=$(printf '%s\n' "$output" | grep -nxF '  SHOPWARE_ES_ENABLED=1' | cut -d: -f1)
    [ -n "$idx" ] && [ -n "$on" ]
    [ "$on" -gt "$idx" ]
    [ "$(printf '%s\n' "$output" | grep -cx '  SHOPWARE_ES_ENABLED=1')" -eq 1 ]
}

# ---------------------------------------------------------------------------
# DATABASE_URL-Skripte
# ---------------------------------------------------------------------------

mysql_stub() {
    printf '#!/bin/bash\nexit 1\n' > "$stub_dir/mysql"
    chmod +x "$stub_dir/mysql"
}

@test "diagnose-slow-queries.sh: DATABASE_URL aus .env.prod.local statt .env.local" {
    printf 'APP_ENV=prod\nDATABASE_URL=mysql://u:p@alt:3306/shop\n' > "$shop/.env"
    printf 'DATABASE_URL=mysql://u:p@lokal:3306/shop\n' > "$shop/.env.local"
    printf 'DATABASE_URL="mysql://u:p@neu:3307/shop"\n' > "$shop/.env.prod.local"
    mysql_stub
    run env -u DATABASE_URL PATH="$stub_dir:$PATH" bash "$DIR/diagnose-slow-queries.sh" http://example.test "$shop"
    [[ "$output" == *"Datenbank: u@neu:3307/shop"* ]]
}

@test "diagnose-slow-queries.sh: ohne DATABASE_URL nennt es alle Quellen, Exit 1" {
    printf 'APP_ENV=prod\n' > "$shop/.env"
    mysql_stub
    run env -u DATABASE_URL PATH="$stub_dir:$PATH" bash "$DIR/diagnose-slow-queries.sh" http://example.test "$shop"
    [ "$status" -eq 1 ]
    [[ "$output" == *"Keine DATABASE_URL gefunden (Umgebung, .env.local.php, .env-Dateien"* ]]
}

@test "diagnose-slow-queries.sh: DATABASE_URL mit \$-Verweis = Exit 69 mit Hinweis" {
    printf 'APP_ENV=prod\nDATABASE_URL="mysql://u:${DB_PASS}@db:3306/shop"\n' > "$shop/.env"
    mysql_stub
    run env -u DATABASE_URL PATH="$stub_dir:$PATH" bash "$DIR/diagnose-slow-queries.sh" http://example.test "$shop"
    [ "$status" -eq 69 ]
    [[ "$output" == *"enthaelt einen \$-Verweis"* ]]
    [[ "$output" != *"Datenbank: u@"* ]]
}

@test "audit-themes.sh: DATABASE_URL aus .env.local.php" {
    printf 'APP_ENV=prod\nDATABASE_URL=mysql://u:p@alt:3306/shop\n' > "$shop/.env"
    printf "<?php return array (\n  'DATABASE_URL' => 'mysql://u:p@php:3306/shop',\n);\n" > "$shop/.env.local.php"
    cat > "$stub_dir/mysql" <<EOF
#!/bin/bash
printf '%s\n' "\$@" >> "$BATS_TEST_TMPDIR/mysql-args"
exit 1
EOF
    chmod +x "$stub_dir/mysql"
    run env -u DATABASE_URL PATH="$stub_dir:$PATH" bash "$DIR/audit-themes.sh" http://example.test "$shop"
    grep -qx -- '-hphp' "$BATS_TEST_TMPDIR/mysql-args"
    ! grep -q -- '-halt' "$BATS_TEST_TMPDIR/mysql-args"
}
